name: UpLeveled Drone
on:
  issue_comment:
    types: [created]

jobs:
  issue_commented:
    name: Puppeteer error reproduction
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Run UpLeveled Drone Script
        run: node upleveled-drone.mjs
